package org.ga4gh;

import org.assertj.core.api.AbstractAssert;

/**
 * {@link BEACON} specific assertions - Generated by CustomAssertionGenerator.
 */
public class BEACONAssert extends AbstractAssert<BEACONAssert, BEACON> {

  /**
   * Creates a new <code>{@link BEACONAssert}</code> to make assertions on actual BEACON.
   * @param actual the BEACON we want to make assertions on.
   */
  public BEACONAssert(BEACON actual) {
    super(actual, BEACONAssert.class);
  }

  /**
   * An entry point for BEACONAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myBEACON)</code> and get specific assertion with code completion.
   * @param actual the BEACON we want to make assertions on.
   * @return a new <code>{@link BEACONAssert}</code>
   */
  public static BEACONAssert assertThat(BEACON actual) {
    return new BEACONAssert(actual);
  }

}
