package org.ga4gh;

import org.assertj.core.api.AbstractAssert;

/**
 * {@link GAReferenceMethods.Callback} specific assertions - Generated by CustomAssertionGenerator.
 */
public class GAReferenceMethodsCallbackAssert extends AbstractAssert<GAReferenceMethodsCallbackAssert, GAReferenceMethods.Callback> {

  /**
   * Creates a new <code>{@link GAReferenceMethodsCallbackAssert}</code> to make assertions on actual GAReferenceMethods.Callback.
   * @param actual the GAReferenceMethods.Callback we want to make assertions on.
   */
  public GAReferenceMethodsCallbackAssert(GAReferenceMethods.Callback actual) {
    super(actual, GAReferenceMethodsCallbackAssert.class);
  }

  /**
   * An entry point for GAReferenceMethodsCallbackAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myGAReferenceMethods.Callback)</code> and get specific assertion with code completion.
   * @param actual the GAReferenceMethods.Callback we want to make assertions on.
   * @return a new <code>{@link GAReferenceMethodsCallbackAssert}</code>
   */
  public static GAReferenceMethodsCallbackAssert assertThat(GAReferenceMethods.Callback actual) {
    return new GAReferenceMethodsCallbackAssert(actual);
  }

}
