package org.ga4gh;

import org.assertj.core.api.AbstractAssert;
import org.assertj.core.internal.Iterables;
import org.assertj.core.util.Objects;

/**
 * {@link GAReadGroupSet} specific assertions - Generated by CustomAssertionGenerator.
 */
public class GAReadGroupSetAssert extends AbstractAssert<GAReadGroupSetAssert, GAReadGroupSet> {

  /**
   * Creates a new <code>{@link GAReadGroupSetAssert}</code> to make assertions on actual GAReadGroupSet.
   * @param actual the GAReadGroupSet we want to make assertions on.
   */
  public GAReadGroupSetAssert(GAReadGroupSet actual) {
    super(actual, GAReadGroupSetAssert.class);
  }

  /**
   * An entry point for GAReadGroupSetAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myGAReadGroupSet)</code> and get specific assertion with code completion.
   * @param actual the GAReadGroupSet we want to make assertions on.
   * @return a new <code>{@link GAReadGroupSetAssert}</code>
   */
  public static GAReadGroupSetAssert assertThat(GAReadGroupSet actual) {
    return new GAReadGroupSetAssert(actual);
  }

  /**
   * Verifies that the actual GAReadGroupSet's classSchema is equal to the given one.
   * @param classSchema the given classSchema to compare the actual GAReadGroupSet's classSchema to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GAReadGroupSet's classSchema is not equal to the given one.
   */
  public GAReadGroupSetAssert hasClassSchema(org.apache.avro.Schema classSchema) {
    // check that actual GAReadGroupSet we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting classSchema of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    org.apache.avro.Schema actualClassSchema = actual.getClassSchema();
    if (!Objects.areEqual(actualClassSchema, classSchema)) {
      failWithMessage(assertjErrorMessage, actual, classSchema, actualClassSchema);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GAReadGroupSet's datasetId is equal to the given one.
   * @param datasetId the given datasetId to compare the actual GAReadGroupSet's datasetId to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GAReadGroupSet's datasetId is not equal to the given one.
   */
  public GAReadGroupSetAssert hasDatasetId(String datasetId) {
    // check that actual GAReadGroupSet we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting datasetId of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    String actualDatasetId = actual.getDatasetId();
    if (!Objects.areEqual(actualDatasetId, datasetId)) {
      failWithMessage(assertjErrorMessage, actual, datasetId, actualDatasetId);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GAReadGroupSet's id is equal to the given one.
   * @param id the given id to compare the actual GAReadGroupSet's id to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GAReadGroupSet's id is not equal to the given one.
   */
  public GAReadGroupSetAssert hasId(String id) {
    // check that actual GAReadGroupSet we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting id of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    String actualId = actual.getId();
    if (!Objects.areEqual(actualId, id)) {
      failWithMessage(assertjErrorMessage, actual, id, actualId);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GAReadGroupSet's name is equal to the given one.
   * @param name the given name to compare the actual GAReadGroupSet's name to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GAReadGroupSet's name is not equal to the given one.
   */
  public GAReadGroupSetAssert hasName(String name) {
    // check that actual GAReadGroupSet we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting name of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    String actualName = actual.getName();
    if (!Objects.areEqual(actualName, name)) {
      failWithMessage(assertjErrorMessage, actual, name, actualName);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GAReadGroupSet's readGroups contains the given GAReadGroup elements.
   * @param readGroups the given elements that should be contained in actual GAReadGroupSet's readGroups.
   * @return this assertion object.
   * @throws AssertionError if the actual GAReadGroupSet's readGroups does not contain all given GAReadGroup elements.
   */
  public GAReadGroupSetAssert hasReadGroups(GAReadGroup... readGroups) {
    // check that actual GAReadGroupSet we want to make assertions on is not null.
    isNotNull();

    // check that given GAReadGroup varargs is not null.
    if (readGroups == null) failWithMessage("Expecting readGroups parameter not to be null.");
    
    // check with standard error message, to set another message call: info.overridingErrorMessage("my error message");
    Iterables.instance().assertContains(info, actual.getReadGroups(), readGroups);

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GAReadGroupSet's readGroups contains <b>only<b> the given GAReadGroup elements and nothing else in whatever order.
   * @param readGroups the given elements that should be contained in actual GAReadGroupSet's readGroups.
   * @return this assertion object.
   * @throws AssertionError if the actual GAReadGroupSet's readGroups does not contain all given GAReadGroup elements.
   */
  public GAReadGroupSetAssert hasOnlyReadGroups(GAReadGroup... readGroups) {
    // check that actual GAReadGroupSet we want to make assertions on is not null.
    isNotNull();

    // check that given GAReadGroup varargs is not null.
    if (readGroups == null) failWithMessage("Expecting readGroups parameter not to be null.");
    
    // check with standard error message, to set another message call: info.overridingErrorMessage("my error message");
    Iterables.instance().assertContainsOnly(info, actual.getReadGroups(), readGroups);

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GAReadGroupSet's readGroups does not contain the given GAReadGroup elements.
   *
   * @param readGroups the given elements that should not be in actual GAReadGroupSet's readGroups.
   * @return this assertion object.
   * @throws AssertionError if the actual GAReadGroupSet's readGroups contains any given GAReadGroup elements.
   */
  public GAReadGroupSetAssert doesNotHaveReadGroups(GAReadGroup... readGroups) {
    // check that actual GAReadGroupSet we want to make assertions on is not null.
    isNotNull();

    // check that given GAReadGroup varargs is not null.
    if (readGroups == null) failWithMessage("Expecting readGroups parameter not to be null.");
    
    // check with standard error message (use overridingErrorMessage before contains to set your own message).
    Iterables.instance().assertDoesNotContain(info, actual.getReadGroups(), readGroups);

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GAReadGroupSet has no readGroups.
   * @return this assertion object.
   * @throws AssertionError if the actual GAReadGroupSet's readGroups is not empty.
   */
  public GAReadGroupSetAssert hasNoReadGroups() {
    // check that actual GAReadGroupSet we want to make assertions on is not null.
    isNotNull();

    // we override the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting :\n  <%s>\nnot to have readGroups but had :\n  <%s>";
    
    // check
    if (actual.getReadGroups().iterator().hasNext()) {
      failWithMessage(assertjErrorMessage, actual, actual.getReadGroups());
    }
    
    // return the current assertion for method chaining
    return this;
  }
  

  /**
   * Verifies that the actual GAReadGroupSet's schema is equal to the given one.
   * @param schema the given schema to compare the actual GAReadGroupSet's schema to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GAReadGroupSet's schema is not equal to the given one.
   */
  public GAReadGroupSetAssert hasSchema(org.apache.avro.Schema schema) {
    // check that actual GAReadGroupSet we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting schema of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    org.apache.avro.Schema actualSchema = actual.getSchema();
    if (!Objects.areEqual(actualSchema, schema)) {
      failWithMessage(assertjErrorMessage, actual, schema, actualSchema);
    }

    // return the current assertion for method chaining
    return this;
  }





}
