package org.ga4gh;

import org.assertj.core.api.AbstractAssert;

/**
 * {@link GAReadMethods} specific assertions - Generated by CustomAssertionGenerator.
 */
public class GAReadMethodsAssert extends AbstractAssert<GAReadMethodsAssert, GAReadMethods> {

  /**
   * Creates a new <code>{@link GAReadMethodsAssert}</code> to make assertions on actual GAReadMethods.
   * @param actual the GAReadMethods we want to make assertions on.
   */
  public GAReadMethodsAssert(GAReadMethods actual) {
    super(actual, GAReadMethodsAssert.class);
  }

  /**
   * An entry point for GAReadMethodsAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myGAReadMethods)</code> and get specific assertion with code completion.
   * @param actual the GAReadMethods we want to make assertions on.
   * @return a new <code>{@link GAReadMethodsAssert}</code>
   */
  public static GAReadMethodsAssert assertThat(GAReadMethods actual) {
    return new GAReadMethodsAssert(actual);
  }

}
