package org.ga4gh;

import org.assertj.core.api.AbstractAssert;

/**
 * {@link GAReferenceMethods} specific assertions - Generated by CustomAssertionGenerator.
 */
public class GAReferenceMethodsAssert extends AbstractAssert<GAReferenceMethodsAssert, GAReferenceMethods> {

  /**
   * Creates a new <code>{@link GAReferenceMethodsAssert}</code> to make assertions on actual GAReferenceMethods.
   * @param actual the GAReferenceMethods we want to make assertions on.
   */
  public GAReferenceMethodsAssert(GAReferenceMethods actual) {
    super(actual, GAReferenceMethodsAssert.class);
  }

  /**
   * An entry point for GAReferenceMethodsAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myGAReferenceMethods)</code> and get specific assertion with code completion.
   * @param actual the GAReferenceMethods we want to make assertions on.
   * @return a new <code>{@link GAReferenceMethodsAssert}</code>
   */
  public static GAReferenceMethodsAssert assertThat(GAReferenceMethods actual) {
    return new GAReferenceMethodsAssert(actual);
  }

}
