package org.ga4gh;

import org.assertj.core.api.AbstractAssert;
import org.assertj.core.internal.Iterables;
import org.assertj.core.util.Objects;

/**
 * {@link GASearchReferencesRequest.Builder} specific assertions - Generated by CustomAssertionGenerator.
 */
public class GASearchReferencesRequestBuilderAssert extends AbstractAssert<GASearchReferencesRequestBuilderAssert, GASearchReferencesRequest.Builder> {

  /**
   * Creates a new <code>{@link GASearchReferencesRequestBuilderAssert}</code> to make assertions on actual GASearchReferencesRequest.Builder.
   * @param actual the GASearchReferencesRequest.Builder we want to make assertions on.
   */
  public GASearchReferencesRequestBuilderAssert(GASearchReferencesRequest.Builder actual) {
    super(actual, GASearchReferencesRequestBuilderAssert.class);
  }

  /**
   * An entry point for GASearchReferencesRequestBuilderAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myGASearchReferencesRequest.Builder)</code> and get specific assertion with code completion.
   * @param actual the GASearchReferencesRequest.Builder we want to make assertions on.
   * @return a new <code>{@link GASearchReferencesRequestBuilderAssert}</code>
   */
  public static GASearchReferencesRequestBuilderAssert assertThat(GASearchReferencesRequest.Builder actual) {
    return new GASearchReferencesRequestBuilderAssert(actual);
  }

  /**
   * Verifies that the actual GASearchReferencesRequest.Builder's accessions contains the given String elements.
   * @param accessions the given elements that should be contained in actual GASearchReferencesRequest.Builder's accessions.
   * @return this assertion object.
   * @throws AssertionError if the actual GASearchReferencesRequest.Builder's accessions does not contain all given String elements.
   */
  public GASearchReferencesRequestBuilderAssert hasAccessions(String... accessions) {
    // check that actual GASearchReferencesRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // check that given String varargs is not null.
    if (accessions == null) failWithMessage("Expecting accessions parameter not to be null.");
    
    // check with standard error message, to set another message call: info.overridingErrorMessage("my error message");
    Iterables.instance().assertContains(info, actual.getAccessions(), accessions);

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchReferencesRequest.Builder's accessions contains <b>only<b> the given String elements and nothing else in whatever order.
   * @param accessions the given elements that should be contained in actual GASearchReferencesRequest.Builder's accessions.
   * @return this assertion object.
   * @throws AssertionError if the actual GASearchReferencesRequest.Builder's accessions does not contain all given String elements.
   */
  public GASearchReferencesRequestBuilderAssert hasOnlyAccessions(String... accessions) {
    // check that actual GASearchReferencesRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // check that given String varargs is not null.
    if (accessions == null) failWithMessage("Expecting accessions parameter not to be null.");
    
    // check with standard error message, to set another message call: info.overridingErrorMessage("my error message");
    Iterables.instance().assertContainsOnly(info, actual.getAccessions(), accessions);

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchReferencesRequest.Builder's accessions does not contain the given String elements.
   *
   * @param accessions the given elements that should not be in actual GASearchReferencesRequest.Builder's accessions.
   * @return this assertion object.
   * @throws AssertionError if the actual GASearchReferencesRequest.Builder's accessions contains any given String elements.
   */
  public GASearchReferencesRequestBuilderAssert doesNotHaveAccessions(String... accessions) {
    // check that actual GASearchReferencesRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // check that given String varargs is not null.
    if (accessions == null) failWithMessage("Expecting accessions parameter not to be null.");
    
    // check with standard error message (use overridingErrorMessage before contains to set your own message).
    Iterables.instance().assertDoesNotContain(info, actual.getAccessions(), accessions);

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchReferencesRequest.Builder has no accessions.
   * @return this assertion object.
   * @throws AssertionError if the actual GASearchReferencesRequest.Builder's accessions is not empty.
   */
  public GASearchReferencesRequestBuilderAssert hasNoAccessions() {
    // check that actual GASearchReferencesRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // we override the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting :\n  <%s>\nnot to have accessions but had :\n  <%s>";
    
    // check
    if (actual.getAccessions().iterator().hasNext()) {
      failWithMessage(assertjErrorMessage, actual, actual.getAccessions());
    }
    
    // return the current assertion for method chaining
    return this;
  }
  

  /**
   * Verifies that the actual GASearchReferencesRequest.Builder's md5checksums contains the given String elements.
   * @param md5checksums the given elements that should be contained in actual GASearchReferencesRequest.Builder's md5checksums.
   * @return this assertion object.
   * @throws AssertionError if the actual GASearchReferencesRequest.Builder's md5checksums does not contain all given String elements.
   */
  public GASearchReferencesRequestBuilderAssert hasMd5checksums(String... md5checksums) {
    // check that actual GASearchReferencesRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // check that given String varargs is not null.
    if (md5checksums == null) failWithMessage("Expecting md5checksums parameter not to be null.");
    
    // check with standard error message, to set another message call: info.overridingErrorMessage("my error message");
    Iterables.instance().assertContains(info, actual.getMd5checksums(), md5checksums);

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchReferencesRequest.Builder's md5checksums contains <b>only<b> the given String elements and nothing else in whatever order.
   * @param md5checksums the given elements that should be contained in actual GASearchReferencesRequest.Builder's md5checksums.
   * @return this assertion object.
   * @throws AssertionError if the actual GASearchReferencesRequest.Builder's md5checksums does not contain all given String elements.
   */
  public GASearchReferencesRequestBuilderAssert hasOnlyMd5checksums(String... md5checksums) {
    // check that actual GASearchReferencesRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // check that given String varargs is not null.
    if (md5checksums == null) failWithMessage("Expecting md5checksums parameter not to be null.");
    
    // check with standard error message, to set another message call: info.overridingErrorMessage("my error message");
    Iterables.instance().assertContainsOnly(info, actual.getMd5checksums(), md5checksums);

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchReferencesRequest.Builder's md5checksums does not contain the given String elements.
   *
   * @param md5checksums the given elements that should not be in actual GASearchReferencesRequest.Builder's md5checksums.
   * @return this assertion object.
   * @throws AssertionError if the actual GASearchReferencesRequest.Builder's md5checksums contains any given String elements.
   */
  public GASearchReferencesRequestBuilderAssert doesNotHaveMd5checksums(String... md5checksums) {
    // check that actual GASearchReferencesRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // check that given String varargs is not null.
    if (md5checksums == null) failWithMessage("Expecting md5checksums parameter not to be null.");
    
    // check with standard error message (use overridingErrorMessage before contains to set your own message).
    Iterables.instance().assertDoesNotContain(info, actual.getMd5checksums(), md5checksums);

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchReferencesRequest.Builder has no md5checksums.
   * @return this assertion object.
   * @throws AssertionError if the actual GASearchReferencesRequest.Builder's md5checksums is not empty.
   */
  public GASearchReferencesRequestBuilderAssert hasNoMd5checksums() {
    // check that actual GASearchReferencesRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // we override the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting :\n  <%s>\nnot to have md5checksums but had :\n  <%s>";
    
    // check
    if (actual.getMd5checksums().iterator().hasNext()) {
      failWithMessage(assertjErrorMessage, actual, actual.getMd5checksums());
    }
    
    // return the current assertion for method chaining
    return this;
  }
  

  /**
   * Verifies that the actual GASearchReferencesRequest.Builder's pageSize is equal to the given one.
   * @param pageSize the given pageSize to compare the actual GASearchReferencesRequest.Builder's pageSize to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchReferencesRequest.Builder's pageSize is not equal to the given one.
   */
  public GASearchReferencesRequestBuilderAssert hasPageSize(Integer pageSize) {
    // check that actual GASearchReferencesRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting pageSize of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    Integer actualPageSize = actual.getPageSize();
    if (!Objects.areEqual(actualPageSize, pageSize)) {
      failWithMessage(assertjErrorMessage, actual, pageSize, actualPageSize);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchReferencesRequest.Builder's pageToken is equal to the given one.
   * @param pageToken the given pageToken to compare the actual GASearchReferencesRequest.Builder's pageToken to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchReferencesRequest.Builder's pageToken is not equal to the given one.
   */
  public GASearchReferencesRequestBuilderAssert hasPageToken(String pageToken) {
    // check that actual GASearchReferencesRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting pageToken of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    String actualPageToken = actual.getPageToken();
    if (!Objects.areEqual(actualPageToken, pageToken)) {
      failWithMessage(assertjErrorMessage, actual, pageToken, actualPageToken);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchReferencesRequest.Builder has accessions.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchReferencesRequest.Builder does not have accessions.
   */
  public GASearchReferencesRequestBuilderAssert hasAccessions() {
    // check that actual GASearchReferencesRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // check
    if (!actual.hasAccessions()) {
      failWithMessage("\nExpecting that actual GASearchReferencesRequest.Builder has accessions but does not have.");
    }
    
    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchReferencesRequest.Builder does not have accessions.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchReferencesRequest.Builder has accessions.
   */
  public GASearchReferencesRequestBuilderAssert doesNotHaveAccessions() {
    // check that actual GASearchReferencesRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // check
    if (actual.hasAccessions()) {
      failWithMessage("\nExpecting that actual GASearchReferencesRequest.Builder does not have accessions but has.");
    }
    
    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchReferencesRequest.Builder has md5checksums.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchReferencesRequest.Builder does not have md5checksums.
   */
  public GASearchReferencesRequestBuilderAssert hasMd5checksums() {
    // check that actual GASearchReferencesRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // check
    if (!actual.hasMd5checksums()) {
      failWithMessage("\nExpecting that actual GASearchReferencesRequest.Builder has md5checksums but does not have.");
    }
    
    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchReferencesRequest.Builder does not have md5checksums.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchReferencesRequest.Builder has md5checksums.
   */
  public GASearchReferencesRequestBuilderAssert doesNotHaveMd5checksums() {
    // check that actual GASearchReferencesRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // check
    if (actual.hasMd5checksums()) {
      failWithMessage("\nExpecting that actual GASearchReferencesRequest.Builder does not have md5checksums but has.");
    }
    
    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchReferencesRequest.Builder has page size.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchReferencesRequest.Builder does not have page size.
   */
  public GASearchReferencesRequestBuilderAssert hasPageSize() {
    // check that actual GASearchReferencesRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // check
    if (!actual.hasPageSize()) {
      failWithMessage("\nExpecting that actual GASearchReferencesRequest.Builder has page size but does not have.");
    }
    
    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchReferencesRequest.Builder does not have page size.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchReferencesRequest.Builder has page size.
   */
  public GASearchReferencesRequestBuilderAssert doesNotHavePageSize() {
    // check that actual GASearchReferencesRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // check
    if (actual.hasPageSize()) {
      failWithMessage("\nExpecting that actual GASearchReferencesRequest.Builder does not have page size but has.");
    }
    
    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchReferencesRequest.Builder has page token.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchReferencesRequest.Builder does not have page token.
   */
  public GASearchReferencesRequestBuilderAssert hasPageToken() {
    // check that actual GASearchReferencesRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // check
    if (!actual.hasPageToken()) {
      failWithMessage("\nExpecting that actual GASearchReferencesRequest.Builder has page token but does not have.");
    }
    
    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchReferencesRequest.Builder does not have page token.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchReferencesRequest.Builder has page token.
   */
  public GASearchReferencesRequestBuilderAssert doesNotHavePageToken() {
    // check that actual GASearchReferencesRequest.Builder we want to make assertions on is not null.
    isNotNull();

    // check
    if (actual.hasPageToken()) {
      failWithMessage("\nExpecting that actual GASearchReferencesRequest.Builder does not have page token but has.");
    }
    
    // return the current assertion for method chaining
    return this;
  }

}
