package org.ga4gh;

import org.assertj.core.api.AbstractAssert;
import org.assertj.core.internal.Iterables;
import org.assertj.core.util.Objects;

/**
 * {@link GASearchReferenceSetsResponse} specific assertions - Generated by CustomAssertionGenerator.
 */
public class GASearchReferenceSetsResponseAssert extends AbstractAssert<GASearchReferenceSetsResponseAssert, GASearchReferenceSetsResponse> {

  /**
   * Creates a new <code>{@link GASearchReferenceSetsResponseAssert}</code> to make assertions on actual GASearchReferenceSetsResponse.
   * @param actual the GASearchReferenceSetsResponse we want to make assertions on.
   */
  public GASearchReferenceSetsResponseAssert(GASearchReferenceSetsResponse actual) {
    super(actual, GASearchReferenceSetsResponseAssert.class);
  }

  /**
   * An entry point for GASearchReferenceSetsResponseAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myGASearchReferenceSetsResponse)</code> and get specific assertion with code completion.
   * @param actual the GASearchReferenceSetsResponse we want to make assertions on.
   * @return a new <code>{@link GASearchReferenceSetsResponseAssert}</code>
   */
  public static GASearchReferenceSetsResponseAssert assertThat(GASearchReferenceSetsResponse actual) {
    return new GASearchReferenceSetsResponseAssert(actual);
  }

  /**
   * Verifies that the actual GASearchReferenceSetsResponse's classSchema is equal to the given one.
   * @param classSchema the given classSchema to compare the actual GASearchReferenceSetsResponse's classSchema to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchReferenceSetsResponse's classSchema is not equal to the given one.
   */
  public GASearchReferenceSetsResponseAssert hasClassSchema(org.apache.avro.Schema classSchema) {
    // check that actual GASearchReferenceSetsResponse we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting classSchema of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    org.apache.avro.Schema actualClassSchema = actual.getClassSchema();
    if (!Objects.areEqual(actualClassSchema, classSchema)) {
      failWithMessage(assertjErrorMessage, actual, classSchema, actualClassSchema);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchReferenceSetsResponse's nextPageToken is equal to the given one.
   * @param nextPageToken the given nextPageToken to compare the actual GASearchReferenceSetsResponse's nextPageToken to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchReferenceSetsResponse's nextPageToken is not equal to the given one.
   */
  public GASearchReferenceSetsResponseAssert hasNextPageToken(String nextPageToken) {
    // check that actual GASearchReferenceSetsResponse we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting nextPageToken of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    String actualNextPageToken = actual.getNextPageToken();
    if (!Objects.areEqual(actualNextPageToken, nextPageToken)) {
      failWithMessage(assertjErrorMessage, actual, nextPageToken, actualNextPageToken);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchReferenceSetsResponse's referenceSets contains the given GAReferenceSet elements.
   * @param referenceSets the given elements that should be contained in actual GASearchReferenceSetsResponse's referenceSets.
   * @return this assertion object.
   * @throws AssertionError if the actual GASearchReferenceSetsResponse's referenceSets does not contain all given GAReferenceSet elements.
   */
  public GASearchReferenceSetsResponseAssert hasReferenceSets(GAReferenceSet... referenceSets) {
    // check that actual GASearchReferenceSetsResponse we want to make assertions on is not null.
    isNotNull();

    // check that given GAReferenceSet varargs is not null.
    if (referenceSets == null) failWithMessage("Expecting referenceSets parameter not to be null.");
    
    // check with standard error message, to set another message call: info.overridingErrorMessage("my error message");
    Iterables.instance().assertContains(info, actual.getReferenceSets(), referenceSets);

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchReferenceSetsResponse's referenceSets contains <b>only<b> the given GAReferenceSet elements and nothing else in whatever order.
   * @param referenceSets the given elements that should be contained in actual GASearchReferenceSetsResponse's referenceSets.
   * @return this assertion object.
   * @throws AssertionError if the actual GASearchReferenceSetsResponse's referenceSets does not contain all given GAReferenceSet elements.
   */
  public GASearchReferenceSetsResponseAssert hasOnlyReferenceSets(GAReferenceSet... referenceSets) {
    // check that actual GASearchReferenceSetsResponse we want to make assertions on is not null.
    isNotNull();

    // check that given GAReferenceSet varargs is not null.
    if (referenceSets == null) failWithMessage("Expecting referenceSets parameter not to be null.");
    
    // check with standard error message, to set another message call: info.overridingErrorMessage("my error message");
    Iterables.instance().assertContainsOnly(info, actual.getReferenceSets(), referenceSets);

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchReferenceSetsResponse's referenceSets does not contain the given GAReferenceSet elements.
   *
   * @param referenceSets the given elements that should not be in actual GASearchReferenceSetsResponse's referenceSets.
   * @return this assertion object.
   * @throws AssertionError if the actual GASearchReferenceSetsResponse's referenceSets contains any given GAReferenceSet elements.
   */
  public GASearchReferenceSetsResponseAssert doesNotHaveReferenceSets(GAReferenceSet... referenceSets) {
    // check that actual GASearchReferenceSetsResponse we want to make assertions on is not null.
    isNotNull();

    // check that given GAReferenceSet varargs is not null.
    if (referenceSets == null) failWithMessage("Expecting referenceSets parameter not to be null.");
    
    // check with standard error message (use overridingErrorMessage before contains to set your own message).
    Iterables.instance().assertDoesNotContain(info, actual.getReferenceSets(), referenceSets);

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual GASearchReferenceSetsResponse has no referenceSets.
   * @return this assertion object.
   * @throws AssertionError if the actual GASearchReferenceSetsResponse's referenceSets is not empty.
   */
  public GASearchReferenceSetsResponseAssert hasNoReferenceSets() {
    // check that actual GASearchReferenceSetsResponse we want to make assertions on is not null.
    isNotNull();

    // we override the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting :\n  <%s>\nnot to have referenceSets but had :\n  <%s>";
    
    // check
    if (actual.getReferenceSets().iterator().hasNext()) {
      failWithMessage(assertjErrorMessage, actual, actual.getReferenceSets());
    }
    
    // return the current assertion for method chaining
    return this;
  }
  

  /**
   * Verifies that the actual GASearchReferenceSetsResponse's schema is equal to the given one.
   * @param schema the given schema to compare the actual GASearchReferenceSetsResponse's schema to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GASearchReferenceSetsResponse's schema is not equal to the given one.
   */
  public GASearchReferenceSetsResponseAssert hasSchema(org.apache.avro.Schema schema) {
    // check that actual GASearchReferenceSetsResponse we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting schema of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    org.apache.avro.Schema actualSchema = actual.getSchema();
    if (!Objects.areEqual(actualSchema, schema)) {
      failWithMessage(assertjErrorMessage, actual, schema, actualSchema);
    }

    // return the current assertion for method chaining
    return this;
  }



}
