package org.ga4gh.methods;

import org.assertj.core.api.AbstractAssert;

/**
 * {@link ReadMethods} specific assertions - Generated by CustomAssertionGenerator.
 */
public class ReadMethodsAssert extends AbstractAssert<ReadMethodsAssert, ReadMethods> {

  /**
   * Creates a new <code>{@link ReadMethodsAssert}</code> to make assertions on actual ReadMethods.
   * @param actual the ReadMethods we want to make assertions on.
   */
  public ReadMethodsAssert(ReadMethods actual) {
    super(actual, ReadMethodsAssert.class);
  }

  /**
   * An entry point for ReadMethodsAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myReadMethods)</code> and get specific assertion with code completion.
   * @param actual the ReadMethods we want to make assertions on.
   * @return a new <code>{@link ReadMethodsAssert}</code>
   */
  public static ReadMethodsAssert assertThat(ReadMethods actual) {
    return new ReadMethodsAssert(actual);
  }

}
