package org.ga4gh.methods;

import org.assertj.core.api.AbstractAssert;
import org.assertj.core.util.Objects;

/**
 * {@link SearchDatasetsRequest} specific assertions - Generated by CustomAssertionGenerator.
 */
public class SearchDatasetsRequestAssert extends AbstractAssert<SearchDatasetsRequestAssert, SearchDatasetsRequest> {

  /**
   * Creates a new <code>{@link SearchDatasetsRequestAssert}</code> to make assertions on actual SearchDatasetsRequest.
   * @param actual the SearchDatasetsRequest we want to make assertions on.
   */
  public SearchDatasetsRequestAssert(SearchDatasetsRequest actual) {
    super(actual, SearchDatasetsRequestAssert.class);
  }

  /**
   * An entry point for SearchDatasetsRequestAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(mySearchDatasetsRequest)</code> and get specific assertion with code completion.
   * @param actual the SearchDatasetsRequest we want to make assertions on.
   * @return a new <code>{@link SearchDatasetsRequestAssert}</code>
   */
  public static SearchDatasetsRequestAssert assertThat(SearchDatasetsRequest actual) {
    return new SearchDatasetsRequestAssert(actual);
  }

  /**
   * Verifies that the actual SearchDatasetsRequest's classSchema is equal to the given one.
   * @param classSchema the given classSchema to compare the actual SearchDatasetsRequest's classSchema to.
   * @return this assertion object.
   * @throws AssertionError - if the actual SearchDatasetsRequest's classSchema is not equal to the given one.
   */
  public SearchDatasetsRequestAssert hasClassSchema(org.apache.avro.Schema classSchema) {
    // check that actual SearchDatasetsRequest we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting classSchema of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    org.apache.avro.Schema actualClassSchema = actual.getClassSchema();
    if (!Objects.areEqual(actualClassSchema, classSchema)) {
      failWithMessage(assertjErrorMessage, actual, classSchema, actualClassSchema);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual SearchDatasetsRequest's pageSize is equal to the given one.
   * @param pageSize the given pageSize to compare the actual SearchDatasetsRequest's pageSize to.
   * @return this assertion object.
   * @throws AssertionError - if the actual SearchDatasetsRequest's pageSize is not equal to the given one.
   */
  public SearchDatasetsRequestAssert hasPageSize(Integer pageSize) {
    // check that actual SearchDatasetsRequest we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting pageSize of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    Integer actualPageSize = actual.getPageSize();
    if (!Objects.areEqual(actualPageSize, pageSize)) {
      failWithMessage(assertjErrorMessage, actual, pageSize, actualPageSize);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual SearchDatasetsRequest's pageToken is equal to the given one.
   * @param pageToken the given pageToken to compare the actual SearchDatasetsRequest's pageToken to.
   * @return this assertion object.
   * @throws AssertionError - if the actual SearchDatasetsRequest's pageToken is not equal to the given one.
   */
  public SearchDatasetsRequestAssert hasPageToken(String pageToken) {
    // check that actual SearchDatasetsRequest we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting pageToken of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    String actualPageToken = actual.getPageToken();
    if (!Objects.areEqual(actualPageToken, pageToken)) {
      failWithMessage(assertjErrorMessage, actual, pageToken, actualPageToken);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual SearchDatasetsRequest's schema is equal to the given one.
   * @param schema the given schema to compare the actual SearchDatasetsRequest's schema to.
   * @return this assertion object.
   * @throws AssertionError - if the actual SearchDatasetsRequest's schema is not equal to the given one.
   */
  public SearchDatasetsRequestAssert hasSchema(org.apache.avro.Schema schema) {
    // check that actual SearchDatasetsRequest we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting schema of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";
    
    // null safe check
    org.apache.avro.Schema actualSchema = actual.getSchema();
    if (!Objects.areEqual(actualSchema, schema)) {
      failWithMessage(assertjErrorMessage, actual, schema, actualSchema);
    }

    // return the current assertion for method chaining
    return this;
  }



}
