package org.ga4gh.models;

import org.assertj.core.api.AbstractAssert;

/**
 * {@link Variants} specific assertions - Generated by CustomAssertionGenerator.
 */
public class VariantsAssert extends AbstractAssert<VariantsAssert, Variants> {

  /**
   * Creates a new <code>{@link VariantsAssert}</code> to make assertions on actual Variants.
   * @param actual the Variants we want to make assertions on.
   */
  public VariantsAssert(Variants actual) {
    super(actual, VariantsAssert.class);
  }

  /**
   * An entry point for VariantsAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myVariants)</code> and get specific assertion with code completion.
   * @param actual the Variants we want to make assertions on.
   * @return a new <code>{@link VariantsAssert}</code>
   */
  public static VariantsAssert assertThat(Variants actual) {
    return new VariantsAssert(actual);
  }

}
